joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50
l1_controller:
  type: "position_controllers/JointPositionController"
  joint: l0_to_l1
l3_controller:
  type: "position_controllers/JointPositionController"
  joint: l2_to_l3
l5_controller:
  type: "position_controllers/JointPositionController"
  joint: l4_to_l5
l7_controller:
  type: "position_controllers/JointPositionController"
  joint: l6_to_l7
